---

- hosts: all
  become: true
  tasks:
  
  - name: install neofetch and apache
    package:
      name:
        - neofetch=6.0.0-2
        - "{{ php_package_name }}"
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: start httpd
    tags: centos
    service:
      name: sttpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS""
    


  - name: remove php support for apache
    package:
      name: "{{ php_package_name }}"
      state: absent